//@ui5-bundle my/company/SimmacoPlugin-ui/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"my/company/SimmacoPlugin-ui/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","my/company/SimmacoPlugin-ui/model/models"],function(e,i,t){"use strict";return e.extend("my.company.SimmacoPlugin-ui.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(t.createDeviceModel(),"device")}})});
},
	"my/company/SimmacoPlugin-ui/controller/View1.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("my.company.SimmacoPlugin-ui.controller.View1",{onInit:function(){UIComponent.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(models.createDeviceModel(),"device");var e=new sap.ushell.ui.shell.ShellHeadItem("supportChatBtn",{icon:sap.ui.core.IconPool.getIconURI("sap-logo-shape"),tooltip:"SAP Portal",showSeparator:true,press:this.onSupportHeaderItemPress});var o=jQuery.sap.getObject("sap.ushell.renderers.fiori2.RendererExtensions");o.addHeaderEndItem(e)},onSupportHeaderItemPress:function(){window.open("https://portal.wdf.sap.corp/irj/portal")},onPress:function(){console.log("**** Test Plugin ****")}})});
},
	"my/company/SimmacoPlugin-ui/i18n/i18n.properties":'title=Title\nappTitle=SimmacoPlugin-ui\nappDescription=App Description',
	"my/company/SimmacoPlugin-ui/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"my.company.SimmacoPlugin-ui","type":"component","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","sourceTemplate":{"id":"html5moduletemplates.basicSAPUI5ApplicationProjectModule","version":"1.40.12"},"crossNavigation":{"inbounds":{"Shell-plugin":{"signature":{"parameters":{},"additionalParameters":"allowed"},"hideLauncher":true,"semanticObject":"Shell","action":"plugin"}}}},"sap.flp":{"type":"plugin"},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"my.company.SimmacoPlugin-ui.view.View1","type":"XML","async":true,"id":"View1"},"dependencies":{"minUI5Version":"1.65.6","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"my.company.SimmacoPlugin-ui.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"my.company.SimmacoPlugin-ui.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteView1","pattern":"RouteView1","target":["TargetView1"]}],"targets":{"TargetView1":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"View1","viewName":"View1"}}}}}',
	"my/company/SimmacoPlugin-ui/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"my/company/SimmacoPlugin-ui/view/View1.view.xml":'<mvc:View controllerName="my.company.SimmacoPlugin-ui.controller.View1" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m"><Shell id="shell"><App id="app"><pages><Page id="page" title="{i18n>title}"><content><Button text="Test" press="onPress" icon="sap-icon://pharmacy"/></content></Page></pages></App></Shell></mvc:View>'
}});
